---
name: Spotify

on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push:

jobs:
  spotify-top-tracks:
    runs-on: ubuntu-latest
    steps:
      - uses: TobiMichael96/spotify-top-tracks@main
